### ISSUE TITLE
Doesn't pass its test suite

### ISSUE THREAD

**Issue by mdorman** [scrive/unjson#1]
Based on the output, I wonder if it might be that this is related to particular versions of underlying libraries, but either way, [this log shows it not passing its test suite](http://hydra.nixos.org/build/40891087/nixlog/2/raw) in the wild.

**Comment by 23Skidoo** [comment]
Looks like the bounds on aeson in the test suite need to be tightened.

**Comment by 23Skidoo** [comment]
As you can see, it passes on Travis with aeson 1.0: https://travis-ci.org/scrive/unjson/jobs/161867201.

**Comment by 23Skidoo** [comment]
Also updated the bounds in the released version on Hackage.
